export const INIT_ORDER = 'Order/INIT_ORDER';

export const FETCH_ORDER = 'Order/FETCH_ORDER';
export const FETCH_ORDER_SUCCESS = 'Order/FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_ERROR = 'Order/FETCH_ORDER_ERROR';

export const CREATE_ORDER = 'Order/CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'Order/CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'Order/CREATE_ORDER_ERROR';

export const DELETE_ORDER = 'Order/DELETE_ORDER';
export const DELETE_ORDER_SUCCESS = 'Order/DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_ERROR = 'Order/DELETE_ORDER_ERROR';

export const DEFAULT_PAGE_SIZE = 12;
