export const INIT_ORGANIZATION = 'Organization/INIT_ORGANIZATION';

export const FETCH_ORGANIZATION = 'Organization/FETCH_ORGANIZATION';
export const FETCH_ORGANIZATION_SUCCESS =
  'Organization/FETCH_ORGANIZATION_SUCCESS';
export const FETCH_ORGANIZATION_ERROR = 'Organization/FETCH_ORGANIZATION_ERROR';

export const CREATE_ORGANIZATION = 'Organization/CREATE_ORGANIZATION';
export const CREATE_ORGANIZATION_SUCCESS =
  'Organization/CREATE_ORGANIZATION_SUCCESS';
export const CREATE_ORGANIZATION_ERROR =
  'Organization/CREATE_ORGANIZATION_ERROR';

export const UPDATE_ORGANIZATION = 'Organization/UPDATE_ORGANIZATION';
export const UPDATE_ORGANIZATION_SUCCESS =
  'Organization/UPDATE_ORGANIZATION_SUCCESS';
export const UPDATE_ORGANIZATION_ERROR =
  'Organization/UPDATE_ORGANIZATION_ERROR';
