export const FETCH_SSA_PRODUCTS = 'SsaProductList/FETCH_SSA_PRODUCTS';
export const FETCH_SSA_PRODUCTS_SUCCESS =
  'SsaProductList/FETCH_SSA_PRODUCTS_SUCCESS';
export const FETCH_SSA_PRODUCTS_ERROR =
  'SsaProductList/FETCH_SSA_PRODUCTS_ERROR';

export const FETCH_PRODUCTS = 'ProductList/FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'ProductList/FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'ProductList/FETCH_PRODUCTS_ERROR';

export const DELETE_PRODUCT = 'ProductList/DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'ProductList/DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'ProductList/DELETE_PRODUCT_ERROR';

export const DELETE_PRODUCTS = 'ProductList/DELETE_PRODUCTS';
export const DELETE_PRODUCTS_SUCCESS = 'ProductList/DELETE_PRODUCTS_SUCCESS';
export const DELETE_PRODUCTS_ERROR = 'ProductList/DELETE_PRODUCTS_ERROR';

export const DEFAULT_PAGE_SIZE = 12;
