export const INIT_PRODUCT = 'Product/INIT_PRODUCT';

export const FETCH_PRODUCT = 'Product/FETCH_PRODUCT';
export const FETCH_PRODUCT_SUCCESS = 'Product/FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERROR = 'Product/FETCH_PRODUCT_ERROR';

export const CREATE_PRODUCT = 'Product/CREATE_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'Product/CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'Product/CREATE_PRODUCT_ERROR';

export const UPDATE_PRODUCT = 'Product/UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'Product/UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR = 'Product/UPDATE_PRODUCT_ERROR';
