export const AUTH_TOKEN_ERROR = 'App/AUTH_TOKEN_ERROR';
export const LOGOUT = 'App/LOGOUT';

export const REGISTER = 'App/REGISTER';
export const REGISTER_SUCCESS = 'App/REGISTER_SUCCESS';
export const REGISTER_ERROR = 'App/REGISTER_ERROR';

export const LOGIN = 'App/LOGIN';
export const LOGIN_SUCCESS = 'App/LOGIN_SUCCESS';
export const LOGIN_ERROR = 'App/LOGIN_ERROR';

export const UPDATE_ACCOUNT = 'App/UPDATE_ACCOUNT';
export const UPDATE_ACCOUNT_SUCCESS = 'App/UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_ERROR = 'App/UPDATE_ACCOUNT_ERROR';
