export const AUTH_TOKEN_ERROR = 'App/AUTH_TOKEN_ERROR';
export const LOGOUT = 'App/LOGOUT';

export const REGISTER = 'App/REGISTER';
export const REGISTER_SUCCESS = 'App/REGISTER_SUCCESS';
export const REGISTER_ERROR = 'App/REGISTER_ERROR';

export const LOGIN = 'App/LOGIN';
export const LOGIN_SUCCESS = 'App/LOGIN_SUCCESS';
export const LOGIN_ERROR = 'App/LOGIN_ERROR';

export const GOOGLE_REGISTER = 'App/GOOGLE_REGISTER';
export const GOOGLE_LOGIN = 'App/GOOGLE_LOGIN';

export const ACTIVATE_ACCOUNT = 'App/ACTIVATE_ACCOUNT';
export const ACTIVATE_ACCOUNT_SUCCESS = 'App/ACTIVATE_ACCOUNT_SUCCESS';
export const ACTIVATE_ACCOUNT_ERROR = 'App/ACTIVATE_ACCOUNT_ERROR';

export const FORGOT_PASSWORD = 'App/FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'App/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'App/FORGOT_PASSWORD_ERROR';

export const RESET_PASSWORD = 'App/RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'App/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'App/RESET_PASSWORD_ERROR';

export const UPDATE_ACCOUNT = 'App/UPDATE_ACCOUNT';
export const UPDATE_ACCOUNT_SUCCESS = 'App/UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_ERROR = 'App/UPDATE_ACCOUNT_ERROR';

export const UPDATE_ORGANIZATION = 'App/UPDATE_ORGANIZATION';
export const UPDATE_ORGANIZATION_SUCCESS = 'App/UPDATE_ORGANIZATION_SUCCESS';
export const UPDATE_ORGANIZATION_ERROR = 'App/UPDATE_ORGANIZATION_ERROR';
